package ch.hcuge.simed.foundation.component.fop;

// Generated by the org.objectstyle.wolips at Fri Jun 03 16:46:35 CEST 2005

import com.webobjects.appserver.*;

import er.extensions.components.ERXComponent;

public class RegionStart extends ERXComponent {

    public RegionStart(WOContext context) {
        super(context);
    }

}